---
title: Quarto Overview
subtitle: A brief overview of Quarto and how we use it to create our website
---

* Background
* What is Quarto? Hopefully, you already have a basic understanding of what Quarto is and how it works, but in case you don't, here is a very brief overview. Quarto is an open-source scientific and technical publishing system built on Pandoc. It allows you to create documents, presentations, websites, and more using simple markdown syntax. We use Quarto to create our websites because it provides a powerful and flexible way to manage our content and publish it in a variety of formats. For example, we can write our tutorials in markdown and then use Quarto to generate HTML pages for our website, as well as PDF, PowerPoint, and Word documents for sharing, printing, and repurposing.
* Quarto is the successor to RMarkdown, and it is designed to be more flexible and powerful than its predecessor. It also has a developing ecosystem of extensions and plugins that allow you to customize your documents and add new features. If you come from a Python background, the Markdown syntax and other features of Quarto should feel familiar, and you can use Python code chunks in your documents just like you would in Jupyter notebooks.
* For a more detailed introduction to Quarto, you can check out the official documentation at <https://quarto.org/docs/>. There are also many tutorials and examples available online that can help you get started with Quarto and learn how to use it effectively for your projects. When it comes to formatting and styling your documents, Quarto provides a lot of options for customizing the appearance of your content. You can use CSS to style your HTML output, and you can also use YAML front matter to specify options for your documents, such as the title, author, date, and more. There is an extensive amount of material to reference in the Quarto guide https://quarto.org/docs/guide/.


* Working with Quarto (specific to the `tutorial-template`):
* We developed the `tutorial-template` repository to provide a standardized starting point for all of our tutorials. This template includes a basic structure for a Quarto project, as well as some pre-configured settings and styles that we use across all of our tutorials. When you create a new tutorial, you can simply clone the `tutorial-template` repository and start editing the content to create your tutorial. The template also includes some helpful scripts and configurations for building and publishing your tutorial, which we will cover in more detail in the following chapters.
    * Our goal with the template is really to make it quick and easy to create new tutorials without having to worry about the technical details of setting up a Quarto project from scratch. By providing a standardized template, we can ensure that all of our tutorials have a consistent look and feel, and we can also make it easier for new authors to get started with creating content for our website.
* We assume you can download and install Quarto on your local machine, but if you have any issues with that, please let us know and we can help you get set up. Once you have Quarto installed, you can use it to create new documents and websites by running the `quarto` command in your terminal with any of the commands found at the command reference page: https://quarto.org/docs/cli/
    * You only need to know sparingly few of these, namely `quarto preview` for previewing the project locally, perhaps `quarto add` for adding extensions, and generally one-time use of `quarto publish` for publishing your project to GitHub Pages (discussed in more detail in the following chapters).
* Here is how we generally expect users to work with a Quarto project:
    * You create a new Quarto project (and in the context of the `tutorial-template`, that simply means cloning the repository and opening it in your code editor).
    * You open the project with your preferred text editor e.g. VS Code, Positron, RStudio. In any case, we expect you to properly *open the project* in your code editor, meaning that you open the folder containing the project files, not just individual files. This is important because it allows your code editor to properly recognize the project structure and provide features like syntax highlighting, file navigation, and so on. Moreover, the terminal in your code editor will be set to the project directory, which is important for running Quarto commands and other scripts that rely on relative file paths.
    * You edit the content of the project, which in the case of the `tutorial-template` primarily means creating and editing `.qmd` files (and including those files in the `_quarto.yml` file to ensure they are included in the website navigation). You can also edit other files in the project, such as CSS files for styling, YAML files for configuration, and so on.
    * You can preview your changes locally by running `quarto preview` in the terminal. This will start a local web server and open your default web browser to display the website. As you make changes to your files and save them, the preview will automatically update to reflect those changes, allowing you to see how your content will look on the live website.
        * We discourage rendering or previewing Quarto documents using the "Render" button in RStudio or the "Run" button in VS Code, as these may not properly render the website and can lead to confusion. Instead, always use `quarto preview` in the terminal to ensure you are seeing an accurate representation of the website.
    * When working on the tutorial, you should aim to use best practices with git and GitHub, meaning that you should create a new branch for your work, make regular commits with descriptive messages, and push your changes to GitHub frequently. This will help you keep track of your changes and make it easier to collaborate with others on the project. See the [Tech Overview](/tech-overview.qmd) tab and the [GitHub Review](/github/review.qmd) page for more information on working with git and GitHub.




* Common features (a reference)

* Including and referencing images: https://quarto.org/docs/authoring/figures.html
* Cross-referencing is highly recommended for tutorials with multiple pages. It allows you to easily link to other pages in your tutorial and ensures that those links will always be up-to-date, even if you change the structure of your tutorial later on. You can learn more about cross-referencing in Quarto here: https://quarto.org/docs/authoring/figures.html#cross-references
* Callout blocks are a great way to highlight important information, provide tips, warnings, and so on. They can help make your content more engaging and easier to read. You can learn how to use callout blocks in Quarto here: https://quarto.org/docs/authoring/callouts.html
* there is tons more to discover in the Authoring and Websites sections of the Quarto guide; feel free to explore them as needed, to ask your favorite LLM, or to ask OSC members for other recommendations on useful Quarto features to use in your tutorial. The features mentioned above, however, are some of the most commonly used features in our tutorials and are a good starting point for new authors to familiarize themselves with Quarto's capabilities. YOu should take the time to familiarize yourself with these features and consider how they can be used to enhance your tutorials and make them more engaging for your audience before you start creating content for your tutorial.