---
title: Updating the OSC Website
---

This chapter contains information and instructions on how to update and add to different sections of the OSC website: <https://www.osc.lmu.de/>

## Pages in this section

| Page | Description |
|---|---|
| [Create a News Item](create-news-item.qmd) | A how-to on adding a News item and overview on the different categories to help you organize them on the website. |
| [Create an Event Page](create-event-page.qmd) | General instructions on adding and organizing Events added to the Event Page. Also contains the different categories of events for better organization. |
| [Create a Profile Page](create-new-members-page.qmd) | Information and instructions for adding a profile for new members that join the OSC. |
| [Adding a New Institutional Member](new-institutional-member.qmd) | Find information here on adding a new institutional member of the OSC as this follows a different process than adding a new individual member. |
| [Edit Other Pages](edit-other-pages.qmd) | This page outlines the general workflow and best practices for editing miscellaneous pages on the OSC website. |
