---
title: "Onboarding a New OSC Member"
---

After a new member has been accepted to the OSC, several administrative tasks must be completed to fully onboard them.

The onboarding process goes beyond creating the member's profile page on the website and ensures that the member is integrated into OSC records, communication channels, and bibliometric tracking systems.

# Onboarding Checklist

After accepting a new member, complete the following tasks:

- [ ] Update the Member Management sheet.
- [ ] Add the member to the Members Publications (Bibliometrics) sheet.
- [ ] Add the member to the appropriate mailing lists.
- [ ] Create a profile page on the OSC website.

# How to Onboard a New Member?

Click through the following tabs to read the details and instructions involved in each item of the checklist:

::: {.panel-tabset}

## Updating the Member Management Sheet

Here is the Google Sheet used to collect and store the information on each OSC member:

- [Member Management Sheet](https://docs.google.com/spreadsheets/d/1dKGtEoSAh0xFkoDdnFUXjjz8ZgFzNSCIsR3q2imuXek/edit?usp=sharing)

To add to the spreadsheet, follow these steps:

1. Select the appropriate worksheet:
   - **OSC-Mitglieder** for LMU and associated members.
   - **Fellows** for OSC fellows.

2. Insert a new row in alphabetical order according to the member's last name.

3. Enter information in columns **A–C**.

4. Copy the formula in **column D** from the member directly above by dragging the cell down.

5. Complete the remaining columns using the information provided in the onboarding email.

### Past Members

When a member leaves the OSC:

1. Remove their entry from the **OSC-Mitglieder** sheet.

2. Add the member to the **Past Members** sheet.

::: {.callout-important}
## Addition to the Newsletter

It is important to indicate the date of onboarding in the Member Management sheet so we can know who are the new memebrs and fellows to introduce in the next newsletter (typically sent bi-annually). "New Members & Fellows" is a recurring category in the OSC Newsletter.
:::

## Updating the Members Publications (Bibliometrics) Sheet

Here is the Google Sheet used to collect and store publications information of each OSC member:

- [Members Publications Sheet](https://docs.google.com/spreadsheets/d/15vXf-iksan44LKMagVAWdcBNnGMtmhk4/edit?gid=293446652#gid=293446652)

To add the bibliometrics of a new member, follow these steps:

1. Check whether the member already exists by searching the sheet for the member's last name. A member is considered to already exist in the system if at least one of their entries has a **1** in both of the first two columns. If the member is already present, simply add any additional OpenAlex IDs if necessary. If the member is not present, continue with the next step.

2. Find the OpenAlex Author ID on the [OpenAlex website](https://openalex.org/). Search for the person by name, affiliation, publications, or research field. In the search results, click the person's name and then select **Author profile**. The URL of the profile page corresponds to the OpenAlex author ID.

Example:

```text
https://openalex.org/authors/A5061123357
```

::: {.callout-tip}
## Alternative Method: Using the R Script

1. Open `01b-Add_members.R`.
2. Modify the search string.
3. Run the script.
4. Inspect the results object to identify the correct OpenAlex author ID.
:::

3. Add the information to the OSC Author List. Add one row for **each valid OpenAlex ID**.

The following cells must be updated:

| Column | Information |
|---------|-------------|
| A | Enter `1` |
| B | Enter `1` |
| C | Enter the `osc_id` |
| E | Enter the OpenAlex ID |
| G | Enter the official `display_name` |

### Creating the `osc_id`

The `osc_id` must:

- be unique for each OSC member;
- remain consistent across all entries for that member.

General rule:

- Use the member's last name only.
- If multiple members share the same last name, append the first initial.

Examples:

```text
Schulz
SchulzC
SchulzE
```

### Formatting the OpenAlex ID

Use the following format:

```text
https://openalex.org/A5061123357
```

**Important:** The ID must:

- contain a capital **A**;
- not contain `/authors/`.

Example:

```text
https://openalex.org/A5061123357
```

### Special Cases

#### If the Person Already Exists

Simply add the new OpenAlex ID.

Example:

```text
1 | 1 | lastname | lastname firstname | OpenAlex ID | firstname lastname
```

## Adding the Member to Mailing Lists

To add the new member to all relevant OSC mailing lists, one needs to be an administrator of those lists. Currently, only Felix and Malika are administrators. 

### Current mailing lists a member may need to be added to

| Name (info page) | Email | Description | Subscription & Posting |
|---|---|---|---|
| [LMU Open Science Center News](https://lists.lrz.de/mailman3/lists/lmu-osc.lists.lrz.de/) | [lmu-osc@lists.lrz.de](mailto:lmu-osc@lists.lrz.de) | Our public community mailing list. | Anyone can subscribe. Only Malika and Felix can post. |
| [Members](https://lists.lrz.de/mailman3/lists/lmu-osc-members.lists.lrz.de/) | [lmu-osc-members@lists.lrz.de](mailto:lmu-osc-members@lists.lrz.de) | For officially onboarded OSC members with a doctoral degree or professorship. Used to announce internal matters. | Only an administrator can add subscribers. Any subscriber can post. |
| [Fellows](https://lists.lrz.de/mailman3/lists/lmu-osc-fellows.lists.lrz.de/) | [lmu-osc-fellows@lists.lrz.de](mailto:lmu-osc-fellows@lists.lrz.de) | For officially onboarded OSC Fellows, including most Carpentries instructors, grassroots initiative leaders, and co-instructors without a PhD. | Only an administrator can add subscribers. Any subscriber can post. |
| [Scientific Board](https://lists.lrz.de/mailman3/lists/lmu-osc-board.lists.lrz.de/) | [lmu-osc-board@lists.lrz.de](mailto:lmu-osc-board@lists.lrz.de) | For members of the OSC Scientific Board (elected every two years). | Only an administrator can add subscribers. Any subscriber can post. |
| [Munich Carpentries Instructors](https://lists.lrz.de/mailman3/lists/carpentries-instructors.lists.lrz.de/) | [carpentries-instructors@lists.lrz.de](mailto:carpentries-instructors@lists.lrz.de) | For certified instructors and helpers who teach computing skills using live coding. | Only an administrator can add subscribers. Any subscriber can post. |

### Procedures

#### Checking if they are already subscriber to our community mailing list

All members and fellows are requested to be part of our news mailing list so they can stay informed and disseminate further our advertisement. To check whether they are already subscribed, sign in to https://lists.lrz.de/mailman3/lists/, select the list, select the tab 'Users > Members' and search for their name. If they aren't there, move on to subscribing them.

#### Subscribe people to relevant mailing lists

Go to 'Mass  operations > mass subscribe', add their email and click 'subscribe users'. It will automatically send them a welcome email. 

Members should be added to the members mailing list, fellows to the fellow mailing list, ect.

#### Custom welcome emails

In the old mailing list system, we use to have custom welcome messages, some including link to onboarding surveys. The new mailing list system (since January 2026) doesn't have this feature. For record the custom messages are provided here in case that feature is reinstated (the formR survey would also need to be reactivated). 

::: {.panel-tabset}

## Community 

Dear new OSC community member

Please take 5 min to fill out this onboarding survey to let us know your preferred mode of participation and type of activities:

https://surveys.osc.lmu.de/OSC-onboarding


In addition to receiving announcements on this mailing list, if you are a member of the LMU, you are also invited to join the Open Science Center workspace on LMU chat (Matrix-Element) to introduce yourself to the community, ask questions, request help, or post announcements.

For this, if you do not already use it with your team, you’ll need to follow the LMU instructions: https://www.lmu.de/en/about-lmu/structure/central-university-administration/it-services-division-vi/it-service-desk/central-it-services/lmu-chat-matrix/.

You can then join the Open Science Center team by following this link: https://matrix.to/#/#lmu-open-science-center:matrix.lmu.de. 


There are two main channels in this workspace.

welcome-and-introduction: please introduce yourself here to establish connections with like-minded people!

community-questions-and-announcements: ask your open science related questions or post announcements of open science related events or opportunities here! In the past, we had questions on e.g. preregistration of pilot study, justification of transparent changes in a preregistration, preregistration for qualitative research, registered report process, predatory journals, open access funds, version control with GitLab, course on unit testing, course on Python, ect. Posting your questions there, instead of emailing them to me, allows me and others to answer you and all of us to benefit from each other’s answers!


If you have any questions or concerns, please email me at malika.ihle@lmu.de 

Best wishes

Malika, OSC coordinator


## Members

Dear new OSC member

This is a mailing list for us to send you specific announcements (e.g. invitation to the annual members' meeting) and for you to send each other opportunities or requests. If in doubt, you can email me with the text you would like to circulate at malika.ihle@lmu.de 

Best wishes
Malika, OSC coordinator

## Fellows 

Dear new OSC Fellow

This is a mailing list for all fellows to exchange opportunities or requests. If in doubt, you can email me with the text you would like to circulate at malika.ihle@lmu.de 

Best wishes
Malika, OSC coordinator

## Carpentry instructor
Dear new Carpentry Instructor 

This is a mailing list for all Carpentries instructors in Munich to exchange opportunities or requests. If in doubt, you can email me with the text you would like to circulate at malika.ihle@lmu.de 

Best wishes
Malika, OSC coordinator

:::


## Creating a Profile Page on the OSC Website

A profile page should be created for every new member.

For detailed instructions, see:

- [Creating a New Member Profile Page](../updating-website/create-new-members-page.qmd)
:::
