---
title: "Switch to Open Program (SwOP)"
---

## General steps to conduct a SwOP

- scoping call: aligning expectations: do they work in R (or willing to learn), will they do a stat course in R, do they want to write a handbook as deliverable
- send SwOP onboarding Survey - pretty similar to Uni-wide survey (minus recruitment questions)
- PI onboarding: align expectations, show them overview content, what their role is in the leading of their team
- group onboarding: present survey results, discuss downsides, conduct the structured interview to understand their specific current workflows
- create flipped classroom schedule, with SOP agreement session per chapter 
- offboarding session: aligning expectation for each team members: current project, next project, for onboarding new members
- offboarding feedback survey to evaluate change in confidence in adoption  

## Material used 

- Memorundum of understanding, structure interview, table of homewwork and all spaces needed for working through the consultations: [SwOP working doc template](https://docs.google.com/document/d/18ngK4SIJE_YFgGk_A9HSpI5Wd_AW2ggdqUm3BASOC6o/edit?usp=sharing)
- onboarding survey: a GitLab repository to which SwOP group members are invited (to see results and quarto report) - template tba
- PI onboarding presentation: google slides - template tba 
- offboarding session: google slides, mural board, prints of the research cycle to work on - template tba 
- feedback survey: a GitLab repository - template tba 

## Lessons Learned and Iterative Improvements

- PI typically does not know much about the concept of these practices and typically nothing at all about their implementation + they needs support to lead their team -> added PI onboarding
- Team needs support assigning who is responsible for what and who can take decisions -> added SOP sessions for each chapters