---
title: "Onboarding an OSC Member"
format: html
---

When onboarding a new member, after adding their profile page to Fiona, the following tasks need to be done to complete the onboarding process:

-   Update the Member Management sheet
-   Add them to the Members Publication (Bibliometrics) sheet
-   Add their contact to the mailing lists
-   Create a profile page on the OSC Quarto Website

## Updating the Member Management Sheet

[Click here to go to the Member Management sheet](https://docs.google.com/spreadsheets/d/1dKGtEoSAh0xFkoDdnFUXjjz8ZgFzNSCIsR3q2imuXek/edit?usp=sharing).

For this sheet, follow these steps:

1.  Choose the correct sheet/tab (OSC-Mitglieder for LMU and Associated members, or Fellows)
2.  Add a new line in the table where the last name of the new member belongs alphabetically
3.  Type in column A-C
4.  Pull down column D from the member above the one you're adding
5.  Fill in all the other columns with the information provided in the initial email

**For past members**: remove the line from the OSC-Mitglieder for LMU and Associated members and add it to the "Past member" sheet.

::: callout-important
## Addition to Newsletter

Also, take note of new added members in the OSC assistants doc under “newsletter” because “new members & fellows” is a category in the OSC Newsletter.
:::

## Updating the Members Publication (Bibliometrics)

[Click here to go to the Members Publication sheet](https://docs.google.com/spreadsheets/d/15vXf-iksan44LKMagVAWdcBNnGMtmhk4/edit?gid=293446652#gid=293446652).

For this sheet, follow these steps:

1.  Check is the person is already added there (search fort the last name). A person is only added if at least one ID has a 1 in the first two rows; if not added yet, continue.
2.  Find the OpenAlex author ID for the new member. Two possible routes (*the first option is recommended*):
  - Go to the [OpenAlex website](https://openalex.org/), search for the person (by name, affiliation, specific works, field of study, etc). At the search result page, click on the elliptic person name --\> "Author profile" on bottom right. The URL of that page is the OpenAlex author id (in the format `https://openalex.org/authors/aXXXXXXXXXX`)
  - Go to 01b-Add_members.R, change the search string, retrieve OpenAlex author ids. Scan the results object for the proper author IDs of the new member.
3.  Add the information to the OSC-authorlist Google sheet. One line for each valid OpenAlex ID. **You need to change 5 cells**:
  -  Enter the osc_id (column C): Make sure, that the osc_id is unique and consistent for each OSC member (i.e., that not multiple osc_ids exist for a single member, and that multiple members with the same last name do not have the same osc_id). Generally use the last name only (you can use umlauts); in case of same last name, add the initial of the first name (as in SchulzC and SchulzE)
  - The OpenAlex ID (column E). You must use a capital "A", and the link without "authors" such as: `https://openalex.org/A5061123357` and not `https://openalex.org/*authors*/a5061123357`
  - The official display_name (column G)
  -  Add a "1" to column A
  -  Add a "1" to column B

**If Person is found**, add OpenAlex ID to the sheet: 1,1, lastname, lastname firstname, ID (just copy the link), firstname lastname

**If no ID has been found**, add to the second sheet "members without OpenAlex ID“

**If more than one person is mixed in one OpenAlex ID**, continue as with no ID but also request a change to the ID outlining the mistake at https://help.openalex.org/hc/en-us/requests/new

## Adding to the Mailing Lists

## Creating a Profile Page on the OSC Quarto Website
