---
title: "Social Media"
format: html
---

## Administration

First thing you do is *create a personal profile* on BlueSky, Mastodon, LinkedIn to be linked in the OSC profile pages. 

::: callout-note
If you don’t want this, you can also log in with the OSC account and we only indicate your name in the profile page of this account (for accountability). 
:::

Ask Malika to give you access to the credentials for the following OSC accounts:

- LinkedIn: <https://www.linkedin.com/company/lmu-open-science-center/?viewAsMember=true>
- Bluesky: <https://bsky.app/profile/lmu-osc.bsky.social/post/3kbhybwivz22q>
- Mastodon: <https://scicomm.xyz/@lmu_osc>
- X is deactivated

The OSC publishes different **categories of posts** on social media:

- Research work from members (e.g. articles)
- Information about various aspects of open science 
- Upcoming events for open science community
- Campaigns for making open science topics more visible

Your main ideas and plans for publishing any campaigns will go into the [main Social Media doc](https://docs.google.com/document/u/0/d/18aIg0UEzhhkycSRIPZLNTflnXUX-H0kaBzMa-dC3V_8/edit)

When you create longer texts or campaigns, create a separate Google doc for that and work in there (?)

Use insights from social media (especially LinkedIn) to scope for new potential members (e.g. view the follower list, see those who liked and commented)

## LinkedIn

Here are some general tips for navigating **LinkedIn**:

- Word limit for posts: 3000

- When including a link in a post, LinkedIn changes it to a link format only recognizable on the platform. So, do **NOT** copy and paste this link from the LinkedIn post to share elsewhere, get the actual link from the source.
- When you make a post on LinkedIn, do not ‘Like’ it from your personal LinkedIn account as an OSC staff member. This prevents the algorithm from promoting it and it would get pushed down.
- Posts with **high-quality pictures** get better engagement. For posts about things like events, talks, big meetings- try and get pictures to post on the social media. 
  - If you are are present at the event, try to get pictures of what's happening or ask if anyone would be willing to take a picture for the social media posts.
  - If you will not be present, contact the people who will be there ahead of time and ask if they could take pictures for a social media post (contact them 1-3 days before to remind them).

## Bluesky

Here are some general tips for navigating **Bluesky**:

- Word limit for posts: 300

- The character limit is restricting so you’d have to often break up a post into a thread of smaller posts. 
- If a post has a resource (e.g. link to a repository, lecture recording, information), try and rework it so that this resource is in the first post of the thread. This makes it better for persons to share or repost the resource and the context around it
  - If you can, make the post with the resource one that can standalone so that when it's reposted, people have the important details in that initial post of the thread. 

## Mastodon

Here are some general tips for navigating **Mastodon**:

- Word limit for posts: 2500
- Limit the use of emojis to lower the chances of the posts being marked as 'AI slop'.  


