---
title: "OSC Public Outreach"
---

This section provides information and instructions on the preparation, execution, and follow-up involved in OSC events such as workshops, Summer Schools, Webinars, and more.

## Pages in this section

| Page | Description |
|---|---|
| [Social Media](social-media.qmd) | This section provides guidance on managing the OSC's social media presence, including account access, content planning, community engagement, and best practices for creating and publishing posts. |
| [Newsletter](newsletter.qmd) | This section provides step-by-step instructions for creating and managing the OSC newsletter in ReallyGoodEmails (formally knows as BeeFree). It includes examples, templates, and recommendations for selecting and preparing newsletter content. |
| [Flyer Design and Images](flyer-design-and-images.qmd) | This page includes resources and guidance for creating visual materials for the OSC, such as flyers, posters, social media graphics, and other promotional content. It also includes information on printing services, design tools, and best practices for image creation. |
