---
title: "Communication"
---

Clear and effective communication is an important part of any event, whether it is to invite a contributor or relay information to participants. This section aims to make this task easier for you by providing information and reusable templates for crafting emails, messages, and other forms of communication when liaising with **guest instructors** and **attendees** of an OSC Event. 

## Liaising with Guest Instructor

Often, we invite external instructors and lecturers to be part of our events. The following will provide you with some guidance when communicating with them via **email**. 

::: {.panel-tabset .nav-pill}

## Template for Initial Email

*Disclaimer: this is a mixture of several emails to give you a clear idea of what needs to be included - carefully pick and choose the appropriate sentences.*

Dear Prof Dr *X*

My name is Malika, I am the coordinator of the LMU Open Science Center *(if they know Felix, add the following: "...whose managing director is Felix Schönbrodt")*.

Based on your work *XX*, we were wondering if you would be willing and available to give a workshop/lecture on *XX* sometimes in *XXMonthsXX*.

I think *XX what would be interesting for our community and why XX* . Usually, PhD students and post docs across many disciplines constitute the core of the audience, but we can limit it to a certain type of research and specify prerequisites if more appropriate.

Would that be of interest to you? Please feel free to suggest any alternative topics. I’m available for a brief Zoom call to define a more precise topic if easier!

We usually run all our events in a hybrid format, with the presenter in person and with me facilitating the online participation. However, solely in person or online events are also possible. Should you be able to come to Munich, we would of course cover your travel and accommodation expenses. We can also cover the travel expense of an additional person you would like to bring to facilitate the workshop with you.

*OR* 

Though all is possible, our workshops are preferentially offered in a hybrid format (I can help with online facilitation) with the presenter in person. If interested, would you be able to come in person? We would pay for your transport and accommodation of course.

A possible time for this event could be *XX-XX*/ from  *XXmonthXX*

I would be grateful if you would let me know either way before *XXtwo weeks laterXX* and if interested, if you could please suggest a few suitable dates!

Thanks and best wishes
Malika 

## Elements of Subsequent Emails

*In another email, after receiving a positive response, confirm specific details*:

- Set a date
- Ask if they need hotel. If yes, then for what night(s) so we can book it
- Let them know they need to book their own train and send us the e-tickets (for reimbursement)
- Ask them for their banking info and address in a specific form to be returned as a Word document

*Get the following information at least one month prior to the event*.

- Title
- Abstract
- Instructor short bio
- Target audience (e.g. field, career stage, dept, interdisciplinary, country)
- Prerequisite (e.g. prior knowledge necessary, software installed)
- Format (e.g. hybrid, in person, online)
- Language (english or german)
- Custom question(s) to ask registrants (e.g. prior knowledge)
- Max number of participants
- Further emails 

Forward them the hotel booking, usually:

Hotel Carlton MunichFürstenstraße 12 <br>
80333 Munich <br>
Tel.: +49 (89) 380 33 76 00 <br>
welcome@hotel-carlton.de

We need an invoice from the hotel with the LMU address and VAT number as found in the credential file… 

LMU Open Science Center <br>
Ludwig-Maximilians-Universität München <br>
Department Psychologie <br>
Leopoldstr. 13, 80802 München <br>
VAT: DE811205325
:::

### Additional Things to Consider

Here's a list of some additional things you may want to communicate to the instructors:

- Send participants' information to instructors who requested it.
- Inform instructors of registration numbers and attendance modes (in-person/online).
- Share any participant preferences or requirements relevant to the session (e.g. R/Julia preference, accessibility needs).
- Ensure instructors have access to required resources (e.g. Zoom links, online workspaces, participant lists).
- Communicate any last-minute changes, cancellations, or waiting list admissions to instructors.
- Support instructors with logistical or technical issues during the event.

## Liaising with Attendees

Communication with attendees or participants happens before, during, and after an OSC event. Liaising with attendees involve advertisement, registration, informational emails, collecting relevant data (e.g. attendance), etc.

Here are useful checklists of things to do and consider:

### Before Event

::: {.panel-tabset .nav-pill}

# Registration & Applications
 
**Registration & Applications**

- [ ] Create **registration page** for the public part of the event (e.g. in-person, online, waiting list for non-members; decide whether registration is per session or for the whole course).
- [ ] If applicants need to apply for specific sessions (e.g. hands-on workshops with limited seats), develop rubrics to score applications.
- [ ] Send registration information and forms to applicants via email.
- [ ] Confirm attendance:
  - [ ] Google Form with name, email, confirmation of attendance, attendance mode, and R/Julia preference.
  - [ ] Google Form for PI approval (if required).
  - [ ] Confirm whether applicants wish to remain on the waiting list.
  - [ ] Create registration page for attendees joining only the public part of the event.
- [ ] Check that registration numbers are reasonable and that registrants selected the correct tickets.
  - [ ] Accept Klinikum registrations if ticket approval is required.
  - [ ] Approve TUM in-person tickets.
  - [ ] Approve additional registrations depending on seat availability.
  - [ ] Email applicants at least two days in advance.
  - [ ] Email the top three people on the waiting list to check whether they are still interested in a last-minute invitation.
  
# Venue & Logistics

**Venue & Logistics**

- [ ] For **in-person receptions**: secure venue, catering, and prepare registration form.
- [ ] Inform local attendees about the in-person reception and registration requirements.
- [ ] Print signage for the in-person venue.

# Communication & Promotion

**Communication & Promotion**

- [ ] Advertise the event through relevant channels, e.g.:
  - [ ] Graduate Center
  - [ ] Infodienst
  - [ ] OSC channels
  - [ ] BlueSky/Mastodon/LinkedIn
  - [ ] UB University of Munich – Central Library
  - [ ] Departmental communication officers mailing list
  - [ ] Follow-up list of communication officers
- [ ] Create an online workspace for attendees (if applicable).
  - [ ] Share the Code of Conduct.
  - [ ] Share password-protected webpages (e.g. Zoom links, private repositories).
  - [ ] Invite LMU participants to the LMU OSC chat space.
- [ ] Send reminder emails to registrants:
  - [ ] When the event becomes fully booked, or
  - [ ] Four days before the event (whichever comes first).
- [ ] Use the registration platform or manually send reminders with relevant information (e.g. Zoom link, abstracts).

:::

::: {.callout-important collapse="true" icon=false}
## Event Fully Booked?

*If the event is fully booked, it is advisable that you communicate that to still interested persons. Here is an email template that you can adapt:*

Dear registrants of the  *XX title of event XX*,

The in-person seats of this event are now booked out and there are already people on the waiting list. Please cancel your seat reservation if you can no longer attend in person by emailing me back or directly on Pretix.

Your participation will remain possible online: *XX zoom link XX*

Meeting ID: *XX*
Passcode: *XX*

We are looking forward to discussing with you soon!

Sincerely,
*XX*
:::

### During Event

- [ ] Manage attendee check-in and registration (if applicable).
- [ ] Ensure signage is displayed appropriately.
- [ ] Monitor attendance and manage any last-minute changes or waiting list admissions.
- [ ] Provide logistical or technical support to participants as needed.
- [ ] Ensure participants have access to online workspaces, Zoom links, and other required resources.

### After Event

- [ ] Follow up with attendees as needed.
- [ ] Archive participant lists, registration forms, and event materials.
- [ ] Close or archive online workspaces and registration platforms if appropriate.




