---
title: "Wrap Up and Feedback"

---

After an event, there are several important follow-up tasks to complete. These include sharing event materials, collecting feedback from participants, and communicating relevant information to instructors.

# Typical Post-Event Workflow

1. Publish the event materials (e.g., slides, recordings, repositories).
2. Send the formr feedback questionnaire to attendees and contributors.
3. Keep the survey open for approximately one week.
4. Generate the feedback report in formr once the survey period has ended.
5. Share the report with instructors and other relevant contributors.
6. Send certificates of completion, if applicable.

::: {.callout-tip}
## Recommendation

When sending feedback requests, keep the survey open for approximately one week and send the email as soon as possible after the event while participants' impressions are still fresh.
:::


## Dissemination of Event Materials

- [ ] Upload event materials (e.g., slides, recordings, handouts) to the appropriate repository, typically a subcomponent of the OSF repository "[Open Science Workshop Materials of the LMU Open Science Center](https://osf.io/zjrhu/overview)"
- [ ] If consent to record was obtained in advance, make recordings publicly available.
- [ ] Advertise the event materials and recordings on OSC mailing lists and social media channels, if appropriate (typically for large events like summer school).

## Creating feedback forms

Feedback should be collected from both attendees (quantitative) and event contributors (qualitative) whenever appropriate.

Templates for feedback forms are available as Gsheet in our Gdrive (e.g. [lectures](https://docs.google.com/spreadsheets/d/1V96I79yGgxIr4nLdyzr0s4JWHGWWo5LKSXt8vMde_Gc/edit?gid=2110598566#gid=2110598566), [workshops or symposia](https://drive.google.com/drive/folders/1jrBRX6GLYdkQVerpMJIOsyrHhc0d6HWC)) to be used in **formr**: <https://formr.osc.lmu.de/>. See the [application chapter](application.qmd) to learn more about formr.


## Communication with Participants

- [ ] Send the feedback survey (usually a formr survey, see the [application chapter](application.qmd) to learn about formr and find some of our templates) to all registrants and ask them to complete it within one week.
- [ ] Include a link to the event materials repository (e.g., recordings, slides, handouts).
- [ ] Provide information about upcoming OSC and co-host events.

## Communication with Instructors

- [ ] Ask for qualitative feedback or a debrief call with all co-instructors 
- [ ] Send the feedback report (generated from the formr survey, see [event evaluation chapter](event-evaluation.qmd)) to instructors.

# Email Templates

## Email to Participants

The following examples can be adapted depending on the event, language, and available materials.

::: {.panel-tabset}

## German Wrap-Up Email Example 1

Liebe Teilnehmerinnen und Teilnehmer des Workshops „XX“,

wenn Sie am Workshop teilgenommen haben, nehmen Sie sich bitte FIXME Zeit, um uns innerhalb einer Woche ein Feedback zu geben:
FIXME Link zum Feedbackformular

Das Material zum Workshop finden Sie hier:
FIXME Link zu den Materialien

Eine Liste aller zukünftigen OSIP- und OSC-Veranstaltungen finden Sie hier:
https://www.osc.lmu.de/events/

Herzliche Grüße,  
Malika

## German Wrap-Up Email Example 2

Liebe Teilnehmerinnen und Teilnehmer von „DEAL zu Diamond“,

vielen Dank für Ihr Interesse und Engagement!

📄 **Materialien**:
Folien sowie das Video von Teil 2 finden Sie auf OSF: https://osf.io/r49ng/files/osfstorage

Die Folien haben eine CC-BY-Lizenz und können gerne nachgenutzt werden.

📝 **Feedback**:
Wir laden Sie herzlich zu einer kurzen (2 Minuten) Umfrage zum Event ein:
Wie hat es Ihnen gefallen? Was würden Sie sich wünschen?
https://surveys.osc.lmu.de/deal-diamond-feedback

📢 **Informiert bleiben**:
Auf unserer Website oder über unsere Mailingliste erhalten Sie Ankündigungen zu zukünftigen Workshops und Symposien des LMU Open Science Center.

🤝 **Mitglied werden**:
Als LMU-Angehörige können Sie sich auch aktiv an unseren Aktivitäten beteiligen, indem Sie Mitglied werden.

Viele Grüße,  
Felix Schönbrodt

## English Wrap-Up Email Example 1

Dear participants of the "XX" workshop,

If you attended the workshop, please take FIXME time to provide us with your feedback within one week: FIXME link to the feedback form

You can find the workshop materials here: FIXME link to the materials

A list of all upcoming OSIP and OSC events can be found here: https://www.osc.lmu.de/events/

Best regards,  
Malika

## Carpentry workshop Wrap up email

Subject: Certificate of Participation Software Carpentry


Dear <<Attendee>>,
Thank you for participating in the recent Software Carpentry Workshop. We appreciate your engagement and contributions during the sessions, and we hope the workshop has provided you with valuable insights and skills.
Attached to this email, you’ll find your certificate of participation.
Additionally, we would like to invite you to explore more self-paced tutorials offered by the LMU Open Science Center. These tutorials are designed to help you continue developing your computing skills and can be reused for your own teaching:
Introduction to R: https://lmu-osc.github.io/introduction-to-R/ 
Version control with Git within RStudio:  https://lmu-osc.github.io/Introduction-RStudio-Git-GitHub/ &  https://lmu-osc.github.io/Collaborative-RStudio-GitHub/ 
Quarto: https://lmu-osc.github.io/introduction-to-Quarto/ 
Introduction to simulation of data analyses in R: https://lmu-osc.github.io/Introduction-Simulations-in-R/ 
Simulations for advanced power analysis in R: https://lmu-osc.github.io/Simulations-for-Advanced-Power-Analyses/  
FAIR data management: https://lmu-osc.github.io/FAIR-Data-Management/  
Code publishing: https://lmu-osc.github.io/code-publishing/    
 
and more, on the LMU Open Science Center GitHub organisation:
https://github.com/lmu-osc 


To receive announcements of future workshops and symposia organised by the LMU Open Science Center (see list of events here: https://www.osc.uni-muenchen.de/events/index.html), please subscribe to the mailing list here:
https://lists.lrz.de/mailman/listinfo/lmu-osc 


:::


# Certificates

Some OSC events (e.g., Carpentry workshops, Summer Schools, or instructor training programs) may require certificates of completion.

Find templates for event certificates in the Google Drive folder here:

- [Templates Folder](https://drive.google.com/drive/folders/1HFmT0RPz6s7Z2DB13rbgREuWatF6I6-J?usp=drive_link)

Certificate templates should be adapted to the specific event, exported as PDF files, and sent to eligible participants after the event.
