---
title: "Income"
---

This page outlines the main procedures for invoicing OSC services and receiving institutional membership fees.

## Invoice for OSC Services

When invoicing for the services provided by the OSC:

1. Obtain a BKZ Number

Obtain a **BKZ number** from:

`OSC Back Office → Finanzuebersicht-Financial_Overview → BKZ`

2. Create the Invoice

Use the **OSC invoice template**.

The invoice must include:

- **VAT number**
- **Rechnung number**
- **BKZ number**
- the appropriate **OSC income account**:

Choose the appropriate account depending on where the payment will come from.

::: {.panel-tabset}

## Within LMU

If the payment will be received from an **LMU account**, use:

**OSC-Einnahmen_LMU**

Kapitel:      1507 <br>
TG:           41 <br>
AOst:         8000812 <br>
Kostenstelle: 110600

## External Organisation

For services provided to an **external organisation**, use:

**OSC-Einnahmen-Ust**

Kapitel:      1507 <br>
TG:           77 <br>
AOst:         805095-7 <br>
Kostenstelle: 11060200
:::

3. Submit the Documentation

- Complete **Muster 01** on **red paper**.
- Submit **Muster 01** to the **Geschäftsstelle (GS)** after sending the invoice.

## Institutional Membership Fees

Request payment through an **invoice**, except for Business Administration, where a **transfer of funds** is used.

Use the following account:

**Haushalt OSC**

Kapitel:      1507 <br>
TG:           40 <br>
AOst:         1106641 <br>
Kostenstelle: 11060200
