---
title: "Administration"
---

::: {.callout-important}
## to-do

1. Lessons learned from Sarah and Sara Lil 
2. Getting LRZ credentials 
3. Getting Psy email
:::

This page contains practical information related to employment at the OSC, including contract administration, office access, and working hour procedures.

# Contract

## Contract Creation

The secretary of Felix's Chair, Lilia Meier, is in charge of creating contracts and liaise with the Department of Psychology's administration. it can require up to 3 months to create a new contract and this requires lots of documentation. She needs to know:

- the number of hours per week
- the date at which to start the contract
- the contract duration (and justification if contract requested is less than a year)
- the OSC funding account
- what university degrees the employee has
- the ending date of their residence permit (if applicable)
- the language they speak (english or german). 

## Contract Renewal (HiWis)

For student assistants (HiWis), preparations for contract renewals should begin **at least 6–8 weeks before the current contract expires**. The same information as above need to be provided.

::: {.callout-important}
## The earlier, the better

Please provide the required information as early as possible to avoid delays in the contract renewal process.
:::

# Transponder Issues

If your transponder stops working or is lost, you can either request a replacement from Malika or visit the **Schliessmedien Office**.

| Information | Details |
|-------------|---------|
| Address | Geschwister-Scholl-Platz 1, Room EZ 008 |
| Opening hours | Tuesday–Thursday, 08:00–11:30 |

If confirmation is required before a new transponder can be issued, contact **Lilia**, who can provide the necessary confirmation as a PDF.

If you lose your tranponder, you will have to pay for a new one as specified in the form signed upon handing over.

# Logging Working Hours

You are generally free to work at the times that are most suitable for you.

However, when assigned a task, please respond within **two days** indicating whether or not you are able to take it on. If you can take on the task, please also provide an estimated timeline for completion.

## Tracking Hours

Use the following template to track your working hours:

- [Working Hours Template](https://docs.google.com/spreadsheets/d/14mOZh3M0XvYzte4neq2CknvnU29HckUL/edit?rtpof=true&sd=true&gid=853702177#gid=853702177)

The template is located in the:

- [Logging Working Hours Folder](https://drive.google.com/drive/folders/15R3RZ4DiHdWOtbbj2w7dd1W2E2N_XkR_?usp=sharing)

### Getting Started

1. Make a copy of the template.
2. Save the copy for your own use.
3. Keep your timesheet up to date and accurately record your hours.

::: {.callout-important}
## Meetings Count as Working Time

Time spent attending OSC meetings counts toward your working hours.
:::

### Additional Uses of the Timesheet

You may also use your timesheet to:

- Mark periods when you are unavailable.
- Estimate how long recurring tasks take for future planning purposes.
- Record important deadlines and milestones.
