---
title: "Staff Onboarding"
---

This chapter is about getting you started with working at the OSC. Use the sections here to familiarize yourself with how the staff communicates, which platforms are useful for specific tasks, and general administrative topics that may come up throughout your time at the OSC. 

In addition to this documentation, you will receive a tailored checklist for your onboarding based on this template [onboarding checklist](https://docs.google.com/document/d/1xDexSCKIPXQShoWx5sJFug0x4L9SNY4oJi-qIywrxRM/edit?usp=sharing). 

While staff are free to organize their todo list however they want, we request that all tasks assigned to student assistants (HiWis) are listed in their respective todo tables in this [OSC assistant todos Gdoc(https://docs.google.com/document/d/11fKrzfCJszaJ7ATK_b_ebb7NRqU53TJMvz4WpJk94Hg/edit?usp=sharing) with deadline, priorities, references to information needed to complete the task, ect., even when they were first discussed in a meeting, over email, or in the LMU chat. HiWis are in turn expected to keep track of their progress there.

## Pages in this section

| Page | Description |
|---|---|
| [Internal Communication](internal-communication.qmd) | This is about the communication channels and meeting spaces used to contact and communicate with other staff members. |
| [Working Environment](working-envi.qmd) | An overview of the platforms we use to organize and store information, materials, workflows, and projects. |
| [Administration](administration.qmd) | General administration information. |
