---
title: "Additional Preparation"
format: html
---

Here is a checklist of additional items to do and consider during prepapration for the event.

- [ ] **If fully or partly online**: test platform with e.g. multiple channels (several per workshops), recordings, transcript, and captioning, guest account for instructors, webinar add-on for lectures 
- [ ] Send notification to Karabulut Seyhan <Seyhan.Karabulut@Verwaltung.Uni-Muenchen.DE>  working for Riesche Barbara <Barbara.Riesche@Verwaltung.Uni-Muenchen.DE> if relevant for post doc across several disciplines to get on Excellerate website
- [ ] Prepare 'welcome' and 'logistics' speech as well as 'welcome' slides, if relevant
- [ ] Practice set up. **For fully or partly online events**, practice random timed break out rooms & recreate or other set up (e.g. hybrid presenters: change microphone, camera, and screen sharing settings) - self-paced or synchronously-led workshops
- [ ] Provide internet access to guests if they can't access eduroam
- [ ] Prepare hybrid networking with specified group numbers
- [ ] Print badges
