---
title: "Logistics within the Event"
format: html
---

Logistics within an event includes the equipment that you may need to use/bring, the technical and physical set ups, guidelines for setting up presentations, and text prompts for speaking. 

## Equipment

Equipment and other materials are usually stored in the grey cabinet in the office or may sometimes be outsourced in advance. The keys for the cabinet are in the top drawer of Malika's desk.

As an assistant, you will need to learn how to:
 
- Use the 360 web conference cameras
- use Zoom in conjunction with external camera, microphones, and handheld microphones that amplify speakers to the room loudspeakers but is still connected to Zoom ([prototype  instructions here](https://docs.google.com/document/d/1W1c0KCm-r26OZ39ep02sMT8HCtAL_V1TeKGW-F1-b00/edit?tab=t.0))
- Be the technical support and online facilitator (welcome people, be available, and be inclusive)
- Create name tags with Word template merged with Excel Sheet list
- Help create formR surveys (application or feedback survey), contact/reserve restaurants, translate announcements, etc.

Here is a list of equipment that you can use to build a checklist for your event:

::: {.callout-note collapse="true" icon=false}
## Potential List of Equipment

- 4 OSC 360 web conference cameras 
  - Kandao 
  - Kandao pro 
  - Owl + extension mic 
  - Kandao from seminar room 3322 (ask Malika for code) 
- 2 UB owls 
- very long HDMI cable (from Malika’s desk) + smaller HDMI cable
- station adapter
- OSC laptop 
- Malika's laptop
- USB stick
- headphones (Malika's & your own personal headphones, if you have)
- Malika’s headphone cable to charge table microphone live if needed 
- 2 tripods
- at least 8 long extension cords with 4 outlets + at least 2 long cords rolled up
- OSC poster
- badges for in person & mixed participants (attendees and presenters and assistants)
- flyers for the signage in Fak 13
- suitcase (to transport the equipment to another building)
- computer mouse
- long internet cable for presenter in case (Malika’s desk)
- red and green stickers 
- your own personal laptop for the hybrid networking event and install necessary software like [barco](https://www.barco.com/na-en/product/clickshare-extension-pack) and [owl labs](https://resources.owllabs.com/app-download) just in case
- external battery 
- huge back pack usually for snacks 
- phone charger + external battery
- tape for cable and also for extension mic package 
- second internet cable 

:::

## Hybrid Events

Equipment for these events include:

- [ ] Owl or Kandao 
  - If do not need a presenter focus mode: Kandao from 3322 can be used; however,
  - If you need a presenter focus mode: you should use Kandao Pro + power cord + cable to laptop + compact adapter (these are usually in a plastic purple bag)
- [ ] table speaker
- [ ] long HDMI cable
- [ ] station/adapter
- [ ] presenter laptop
- [ ] suitcase
- [ ] USB stick
- [ ] headphones 
- [ ] (recommendation) a little box for raising camera (20 cm)

::: {.callout-note collapse="true" icon=false}
## What to do?

- [ ] Connect Kandao or Owl to power and to presenter laptop
- [ ] Turn the beamer on and connect the laptop to it
- [ ] If Kandao Pro, then turn it on (button on the device)
- [ ] Open Zoom (link is likely in your calendar invite or last email reminder to registrants)
- [ ] Make sure sound and video in Zoom are *set* to Kandao
- [ ] Decide whether to have a duplicated or extended display (laptop display setting). 
  - **extended display**: can share the projected screen in Zoom, and transfer there what the participants in the room and online need to see, while seeing other things on the laptop screen (e.g. PowerPoint presenter notes, chat, participants, videos from other participants)
  - **duplicated display**: what you see on your laptop screen is what everybody sees (e.g. chat and other participants video). This is useful when the in person and online participants should interact and you want to see it e.g. questions on your laptop screen and not just on the projected screen. 
- [ ] Test sound for online participants
  - Ask an online participants if they can hear you and people furthest in the room, otherwise bring in-person participants and Kandao closer to each other 
  - Ask an online participant to speak and possibly adjust the Kandao volume (button on device)
  - **If another person in the room is the online tester**, they should wear headphones or get outside of the room. If they keep checking the online audio during the event, they should wear headphones and, if they stay in the zoom room without headphones, they should mute their laptop (in addition to muting zoom).
- [ ] Decide on Kandao camera view or ‘mode’ (button on device, and on the remote for Kandao Pro)
  - use presenter focus mode for presentation and recording (Kandao Pro)
  - keep 2x180° view for Q&A and interactive parts
  
:::

**In-Person Speaker Logistics**:

- Tech Laptop
  - Unmute microphone
  - Pin “Kandao” window as spotlight for everyone.
  - Turn off speaker (i.e., mute the device in the system settings) to avoid feedback loop (different from unmuting the microphone).
- Local settings
  - Presenters should use the small room microphone.
  
**Remote/Online Speaker Logistics**:

- Tech Laptop
  - Pin “presenting” window as spotlight for everyone.
  - Mute microphone
- Send Zoom window to the beamer; make Zoom window fullscreen
- Turn on the Jabra speaker volume (so that the in-person audience can hear the online panelists); i.e. unmute the laptop, not the microphone

## Summer School

The **Open Science Summer School** is an annual week-long program put on by the OSC to teach participants about open science and open research topics, practices, tools, and more! Let's break down the preparation for this event:

::: {.panel-tabset}

### Room Set Up

- [ ] table in classroom style for 26 attendees 
- [ ] table microphone (1 per 6 people)
- [ ] high chair and high table for the presenter (instead of or together with the podium)
- [ ] high chairs and high table in the back 
- [ ] tea, coffee, snacks, napkins, trash  in kitchen
- [ ] cabinet in the front for badges, box/bag for attendees to give money

### Electronics Set Up

- [ ] switch on system creston - `anlage ein` & `projektor ein`
- [ ] connect 360 web conference cameras (Owl for lectures, Kandao Pro for workshops) on tripod to laptop
- [ ] click-and-share device to laptop. Make sure the laptop has the necessary software ([Barco-clickshare-extension](https://www.barco.com/na-en/product/clickshare-extension-pack) and [Owl App](https://resources.owllabs.com/app-download) on the presenters laptop.
- [ ] set up table mic for presenter
- [ ] Sharing Screen to Beamer 
  - duplicate or extended display (in laptop setting-display-multiplay displays)
  - click on “extend these displays”
- [ ] Powerpoint: set to presenter view 
  - in power point presenter mode, click show taskbar to see the other apps
  - => not sharing powerpoint, but share second screen in Zoom

In case the screen is not projected (e.g. after changing from duplicated to extended display) - click again on the click and share button. Possibly, you need to unplug the click and share and plug it back in. If it still doesn't work, change outlet for the click and share (try USB, or usbc from laptop). 

### Zoom Set Up

- [ ] make OSC assistant the Co Host always
- [ ] in `participant tab`, click on ellipsis for the following settings:
  - Untick play sound when someone joins or leaves 
  - allow participants to raise hand (in webinar)
  - allow panelist to share video (in webinar)
  - attendees view follow host view (in webinar)
- [ ] in `Q&A tab`: 
  - allow attendees to view all question
  - tick for upvote and comment
  - tick for ask anonymous questions
- [ ] for the `chat`: 
  - everybody can chat with everybody
- [ ] when sharing screen  in zoom, click ‘more’ to see the option to hide floating meeting controls (to make them return, click `Esc` (key top left of keyboard))
- [ ] may sometimes require the option: “Doppelmonitore”/”dual screens” found in the Zoom account, profile setting

### Lectures Set Up

*Use Kandao Pro for lectures*

**In-Person Presenter**

- [ ] tell them to always speak facing the microphone, not the projected screen, and point to the screen only using the mouse and not a pointer on the projected screen.
- [ ] ask them if they prefer *duplicated* (which they’ll likely need if they're using a PDF instead of PowerPoint, or during workshop if they share their screen often) or *extended* screen (needed for presenter mode of PowerPoint)
- [ ] ask if they need to share their sound when sharing their screen (if they want to play a video, for e.g.). For this, the Zoom sharing window selection has a tick box at the bottom to say ‘`optimize for video/sound sharing`’
- [ ] in Zoom: use Owl or Kandao Pro as camera (on presenter mode in settings during the presentation; focus mode + 360° view for the Q&A. Ensure the presenter is pinned/spotlight for everyone in Zoom), 
- [ ] test the speaker (which would be the room speaker) and microphone (which would be the table microphone) 
  - click and share, room audio, crestron
  
**Online Presenter**

- [ ] check audio: crestron for Zoom (mute microphone)
  - when changing audio, follow these steps: Crestron -> Audio -> Barco (volume) (you can test it on Zoom using "Testing mic speaker" feature)
- [ ] view (top right corner in Zoom): use `side by side speaker` and pin/spotlight the speaker for everyone
- [ ] sharing screen: set Zoom window on second display, view, full screen (to exit full screen click esc (top left key on keyboard) (?)
- [ ] zoom: mouse on zoom (for using shortcuts) (?)
  - OSC assistant should pin Malika's video and the online presenter when she introduces them  (Ellipsis on the video feed -> pin), then spotlight the presenter for everyone during their presentation
  - Then again pin both the video for the room and the presenter for the Q&A.
  - The view of the room should be focus presenter mode when introduction (as it is recorded), then 2x180° on the Kandao Pro during Q&A (not recorded)- this can be changed clicking ‘mode’ on the remote (after the remote is turned on).
- [ ] make sure audio in the room has the right volume

### Workshop Set Up

- [ ] Kandao setting/mode: 2x180°
- [ ] prepare Zoom breakout rooms if needed with appropriate names and settings

**In-Person Instructor**

- [ ] connect their laptop (reminder, they need the necessary software [Barco-clickshare-extension](https://www.barco.com/na-en/product/clickshare-extension-pack) and [Owl App](https://resources.owllabs.com/app-download) depending on what camera or projector they will use).
- [ ] If discussion based, project the Zoom windows with online participants (dual monitor can be helpful here) 

online instructor present at the venue (?)
set them up in the small back room? need headphones 

::: 

**Webinars/Lectures** <br>
During Each Session: 

- START RECORDING before Malika introduce presenters
- STOP RECORDING when presentation is done, before Q&A
  - Upload the recording and slides right after the lectures on a subrepository of the grassroot initiative organizing the workshop (e.g. OSIP: https://osf.io/mgwk8/ ; OSC: https://osf.io/zjrhu/)
  - consent from the presenter should have been obtained beforehand using this [written consent form](https://docs.google.com/document/d/1vtK-TFtcf-bpKdA7YD9b6WxTYPzhTGPb/edit)
- If any app crashes, use: `strg + alt + entf OR Ctrl + Alt + Del -> task manager -> end task` (especially for Zoom) then rejoin the meeting and take it slow 
- check if you are the co-host
- rename to "OSC Assistant"
- pin Malika when introducing presenters as well as online presenter - then spotlight presenter for everyone
- May sometimes send messages like: 
  - "If there is any logistical problem please let us know!" 
  - "Please feel free to ask and upvote questions in the Q&A box!"
- one assistant to check sound (in headphones) and visuals for the online audience at all times using the OSC laptop or personal laptop. Their laptop speakers must be turned off. 
- collect resources shared in the chat and add them to the Summer School central doc 

::: callout-warning
## Sharing the Central Doc Link

Do not share this link in the `webinar` (lectures) Zoom room but you can share it in the `meeting` (workshops) Zoom room
:::

- Take attendance using the Google Sheet with selected applicants list for each session
  - make note of total number of attendance (and range)
  
End of Each Session:

- Send a message in the group chat saying:
  - when the next public lecture will be
  - what the next session of the Summer School will be and when
  - whether the next session is for registered participants
- Pre-write all the texts for the days so you can copy and paste them in the chat. 

::: {.callout-note collapse="true" icon=false}
## Examples of Zoom Chat Messages

*Welcome:* <br>
Welcome! The presentation is recorded (not the Q&A). Feel free to say hi and where you are joining us from, and to share resources in the chat (which we will collect). Please ask and upvote questions in the Q&A box! 

Welcome to this workshop! If you have any questions about the content of the workshop, feel free to post them in the Q&A box.

*Questions:* <br>
If you have any questions, feel free to post them in the Q&A box.

*Goodbye:* <br>
Thank you for your attendance. We will continue with our talk on credible research in 10 minutes (11:00 am CEST) on the same Zoom link. 

:::

**At the End of Each Day**

- [ ] bring all table mics to be charged
- [ ] charge headphones
- [ ] turn off the system
- [ ] clean up snack table and trash
- [ ] fill up and run dishwasher










